# Generated by Django 5.1.2 on 2024-10-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aula', models.PositiveIntegerField(unique=True)),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(choices=[('p', 'Professor'), ('d', 'Direção'), ('c', 'Coordenação')], max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('ult_acesso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('turma', models.CharField(blank=True, max_length=50, null=True)),
                ('data_hora_reserva', models.DateTimeField(auto_now_add=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.espaco')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.horario')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
        ),
    ]
